In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
original_df = pd.read_csv('e:NetFlix.csv')

In [3]:
df = original_df.copy()

In [4]:
df.sample(5)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,genres,description
6284,s6655,Movie,The Meaning of Monty Python,Albert Sharpe,NaN,United Kingdom,2-Oct-18,2013,TV-MA,60,Documentaries,Five Pythons reflect on their creative process...
5836,s6251,TV Show,The Crime,NaN,"Magdalena Boczarska, Wojciech Zieliński, Joann...",Poland,26-Nov-19,2015,TV-MA,2,"Crime TV Shows, International TV Shows, TV Dramas",The peaceful lives of the residents inhabiting...
913,s1820,Movie,Don't Look Down,Daniel Gordon,Richard Branson,United Kingdom,1-Apr-17,2016,TV-MA,93,"Documentaries, International Movies",Aided by dramatic reconstructions and archive ...
4792,s5311,Movie,Russell Howard: Recalibrate,Peter Orton,Russell Howard,United Kingdom,19-Dec-17,2017,TV-MA,69,Stand-Up Comedy,Self-deprecating comic Russell Howard plows ah...
5058,s5551,Movie,Shawn Mendes: Live in Concert,Paul Dugdale,Shawn Mendes,"United Kingdom, United States",25-Nov-20,2020,TV-PG,87,Music & Musicals,"In his hometown of Toronto, Shawn Mendes pours..."

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7787 entries, 0 to 7786
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       7787 non-null   object
 1   type          7787 non-null   object
 2   title         7787 non-null   object
 3   director      5398 non-null   object
 4   cast          7069 non-null   object
 5   country       7280 non-null   object
 6   date_added    7777 non-null   object
 7   release_year  7787 non-null   int64
 8   rating        7780 non-null   object
 9   duration      7787 non-null   int64
 10  genres        7787 non-null   object
 11  description   7787 non-null   object
dtypes: int64(2), object(10)
memory usage: 730.2+ KB

In [6]:
df.describe()

       release_year     duration
count   7787.000000  7787.000000
mean    2013.932580    69.122769
std        8.757395    50.950743
min     1925.000000     1.000000
25%     2013.000000     2.000000
50%     2017.000000    88.000000
75%     2018.000000   106.000000
max     2021.000000   312.000000

In [7]:
df.duplicated().value_counts()

False    7787
Name: count, dtype: int64

In [8]:
df.isnull().sum()

show_id            0
type               0
title              0
director        2389
cast             718
country          507
date_added        10
release_year       0
rating             7
duration           0
genres             0
description        0
dtype: int64

## cleaning 'director' column

In [9]:
df['director'].isnull().value_counts()

director
False    5398
True     2389
Name: count, dtype: int64

In [10]:
df['director'] = df['director'].fillna('unknown')

In [11]:
df['director'].notnull().value_counts()

director
True    7787
Name: count, dtype: int64

In [12]:
df.loc[df['director']=='unknown' , ['type','genres']]

         type                                             genres
0     TV Show  International TV Shows, TV Dramas, TV Sci-Fi &...
4     TV Show  British TV Shows, Docuseries, Science & Nature TV
10    TV Show               Anime Series, International TV Shows
15    TV Show                                           Kids' TV
17    TV Show                                           TV Shows
...       ...                                                ...
7777  TV Show  Crime TV Shows, International TV Shows, TV Dramas
7779  TV Show              TV Dramas, TV Mysteries, TV Thrillers
7780  TV Show    International TV Shows, TV Horror, TV Mysteries
7782  TV Show                 International TV Shows, Reality TV
7783  TV Show               Anime Series, International TV Shows

[2389 rows x 2 columns]

## cleaning the cast column

In [13]:
df['cast'].isnull().value_counts()

cast
False    7069
True      718
Name: count, dtype: int64

In [14]:
df['cast'].unique()

array(['João Miguel, Bianca Comparato, Michel Gomes, Rodolfo Valente, Vaneza Oliveira, Rafael Lozano, Viviane Porto, Mel Fronckowiak, Sergio Mamberti, Zezé Motta, Celso Frateschi',
       'Rajneesh Duggal, Adah Sharma, Indraneil Sengupta, Anjori Alagh, Rajendranath Zutshi, Vipin Sharma, Amin Hajee, Shri Vallabh Vyas',
       'Reza Rahadian, Bunga Citra Lestari, Tara Basro, Chelsea Islan',
       ...,
       'Léa Seydoux, Adèle Exarchopoulos, Salim Kechiouche, Aurélien Recoing, Catherine Salée, Benjamin Siksou, Mona Walravens, Alma Jodorowsky, Jérémie Laheurte, Anne Loiret, Benoît Pilot, Sandor Funtek, Fanny Maurin',
       'Cate Blanchett, Sally Hawkins, Alec Baldwin, Louis C.K., Bobby Cannavale, Andrew Dice Clay, Peter Sarsgaard, Michael Stuhlbarg, Tammy Blanchard, Max Casella, Alden Ehrenreich',
       'Sarah Paulson, Mark Duplass, Clu Gulager'],
      shape=(6832,), dtype=object)

In [15]:
df['cast'] = df['cast'].fillna('unknown')

In [16]:
df['cast'].notnull().sum()

np.int64(7787)

## cleaning country

In [17]:
df['country'].isnull().sum()

np.int64(507)

In [18]:
df['country'] = df['country'].fillna('unknown country')

In [19]:
df['country'].notnull().sum()

np.int64(7787)

## cleaning rating

In [20]:
df['rating'].isnull().sum()

np.int64(7)

In [21]:
df['rating'].unique()

array(['TV-MA', 'TV-PG', 'R', 'TV-G', 'PG-13', 'TV-14', 'TV-Y', 'PG',
       'TV-Y7', 'NR', 'G', 'TV-Y7-FV', nan, 'UR', 'NC-17'], dtype=object)

In [22]:
df['rating'].isnull().sum()

np.int64(7)

In [23]:
df['rating'] = df['rating'].fillna('unrated')

In [24]:
df['rating'].isnull().sum()

np.int64(0)

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7787 entries, 0 to 7786
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       7787 non-null   object
 1   type          7787 non-null   object
 2   title         7787 non-null   object
 3   director      7787 non-null   object
 4   cast          7787 non-null   object
 5   country       7787 non-null   object
 6   date_added    7777 non-null   object
 7   release_year  7787 non-null   int64
 8   rating        7787 non-null   object
 9   duration      7787 non-null   int64
 10  genres        7787 non-null   object
 11  description   7787 non-null   object
dtypes: int64(2), object(10)
memory usage: 730.2+ KB

In [27]:
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,genres,description
0,s1,TV Show,3%,unknown,"João Miguel, Bianca Comparato, Michel Gomes, R...",Brazil,14-Aug-20,2020,TV-MA,4,"International TV Shows, TV Dramas, TV Sci-Fi &...",In a future where the elite inhabit an island ...
1,s10,Movie,1920,Vikram Bhatt,"Rajneesh Duggal, Adah Sharma, Indraneil Sengup...",India,15-Dec-17,2008,TV-MA,143,"Horror Movies, International Movies, Thrillers",An architect and his wife move into a castle t...
2,s100,Movie,3 Heroines,Iman Brotoseno,"Reza Rahadian, Bunga Citra Lestari, Tara Basro...",Indonesia,5-Jan-19,2016,TV-PG,124,"Dramas, International Movies, Sports Movies",Three Indonesian women break records by becomi...
3,s1000,Movie,Blue Mountain State: The Rise of Thadland,Lev L. Spiro,"Alan Ritchson, Darin Brooks, James Cade, Rob R...",United States,1-Mar-16,2016,R,90,Comedies,New NFL star Thad buys his old teammates' belo...
4,s1001,TV Show,Blue Planet II,unknown,David Attenborough,United Kingdom,3-Dec-18,2017,TV-G,1,"British TV Shows, Docuseries, Science & Nature TV",This sequel to the award-winning nature series...

# feature engineering

### fe for 'date_added' column

In [28]:
df['date_added'] = pd.to_datetime(df['date_added'],errors='coerce') #errors='coerce': Valid date = converted properly , Invalid date = replaced with NaT

df['year_added'] = df['date_added'].dt.year # '.dt is a datetime accessor in pandas'
df['month_added'] = df['date_added'].dt.month
df['day_added'] = df['date_added'].dt.day

C:\Users\shrey\AppData\Local\Temp\ipykernel_2728\2999940046.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['date_added'] = pd.to_datetime(df['date_added'],errors='coerce') #errors='coerce': Valid date = converted properly , Invalid date = replaced with NaT

## fe for 'country' column

In [29]:
#df['country'].unique()

In [30]:
df['country_count'] = df['country'].apply(lambda x: len(x.split(',')))

In [31]:
df['country_count']

0       1
1       1
2       1
3       1
4       1
       ..
7782    1
7783    1
7784    3
7785    1
7786    1
Name: country_count, Length: 7787, dtype: int64

## fe for rating

In [35]:
#Group into categories (better analysis)
def categorize_rating(r):
    if r in ['TV-Y', 'TV-Y7', 'TV-Y7-FV', 'G']:
        return 'Kids'
    elif r in ['TV-G', 'TV-PG', 'PG']:
        return 'Family'
    elif r in ['TV-14', 'PG-13']:
        return 'Teen'
    elif r in ['TV-MA', 'R', 'NC-17']:
        return 'Adult'
    else:
        return 'Unknown'

df['rating_category'] = df['rating'].apply(categorize_rating)

In [32]:
#df['genres'].unique()

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7787 entries, 0 to 7786
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   show_id        7787 non-null   object
 1   type           7787 non-null   object
 2   title          7787 non-null   object
 3   director       7787 non-null   object
 4   cast           7787 non-null   object
 5   country        7787 non-null   object
 6   date_added     7777 non-null   datetime64[ns]
 7   release_year   7787 non-null   int64
 8   rating         7787 non-null   object
 9   duration       7787 non-null   int64
 10  genres         7787 non-null   object
 11  description    7787 non-null   object
 12  year_added     7777 non-null   float64
 13  month_added    7777 non-null   float64
 14  day_added      7777 non-null   float64
 15  country_count  7787 non-null   int64
dtypes: datetime64[ns](1), float64(3), int64(3), object(9)
memory usage: 973.5+ KB